# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

version: '3.2'
services:
  dbuf:
    build: .
    image: registry.aetherproject.org/tost/dbuf:latest
    ports:
      - "10000:10000"
    command: "dbuf -notify_timeout 3s"

  dbuf-client:
    build: .
    command: "dbuf-client -url dbuf:10000 -local_dataplane_url dbuf-client:2153 -remote_dataplane_url dbuf:2152 -demo 10s -notify_timeout 3s"
    depends_on:
      - dbuf
